# Site settings
title: Atticus White - Wordpress Developer, Boston MA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Atticus is a Boston Wordpress developer, Magento and Shopify developer for ecommerce stores,
  and AngularJS + PHP software engineer for web applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://atticuswhite.com" # the base hostname & protocol for your site
twitter_username: atticoos
github_username:  ajwhite

collections:
  projects:
    output: true
    permalink: /projects/:path/

permalink: /:categories/:title

tags:
- gulpjs
- angularjs

# Build settings
markdown: kramdown
source: src
destination: public
gems:
- jekyll-sitemap
exclude:
- bower_components
- node_modules
- package.json
- bower.json
- Gemfile
- Gemfile.lock
keep_files:
- dist
